### ISSUE TITLE
Injecting 'fs' into 'isomorphic-git' instead of global?

### ISSUE THREAD

**Issue by billiegoose** [MatrixAI/js-virtualgit#2]
> So isomorphic git starts with a git constructor that is git(), and it creates a "git" context object. This object essentially starts at a particular directory at the filesystem, it makes use of fs, and if you globally override the fs api it will just work. In my case, I just want git in-memory, so instead I want the fs api to be passed in instead of being expected to just exist as a global, that avoids needing to wrap things and using babel rewire.

I totally get that. In fact, there is only one place in `isomorphic-git` that uses `fs` ... https://github.com/wmhilton/isomorphic-git/blob/master/src/utils/fs.js

```js
import systemfs from 'fs'
export default function () {
  return global.fs || systemfs
}
```

Tell you what I'll could do. I could make 'fs' an optional argument to each of the commands. For example, currently here's a snippet from git add:

```js
import { fs, read } from '../utils'

export async function add ({ gitdir, workdir, filepath }) {
```

I could tweak it like so:

```js
import { fs as defaultfs, read } from '../utils'

export async function add ({ gitdir, workdir, filepath, fs = defaultfs}) {
```

et voila! Dependency on the global is no more.

---

Then to simplify the high-level API, we could export a new constructor that accepts an options argument and pass that 'fs' as an option when you create a new instance.

```js
import { Git } from 'isomorphic-git'
const git = new Git({fs})
```

**Comment by CMCDragonkai** [comment]
That would be pretty nice. So you essentially you have a file representing "default options" to the main constructor.

**Comment by billiegoose** [comment]
>  that avoids needing to wrap things and using babel rewire.

The automatic "fs" detection bit me in the behind yesterday - I spent an hour trying to figure out why it wasn't working in a ServiceWorker. Answer: because window.fs wasn't defined in that scope. (I'd written `const window = self` instead of `var window = self`, forgetting the scoping rules of const.)

I'm going to work on this today.

**Comment by billiegoose** [comment]
I finished the big refactoring. You now use `isomorphic-git` like this:

```js
import { Git, fetch, push, ... } = require('isomorphic-git')
...

let repo = new Git({fs, dir})
await fetch(repo, fetchOptions);
...

await push(repo, pushOptions);
...
```

This was a compromise between having `new Git()` return the kitchen sink of all functionality (bad for bundle size) and having to pass `fs`, `gitdir`, and `workdir` every time. What do you think? Will the new API work better for your project? [new isomorphic-git API documentation website](https://wmhilton.github.io/isomorphic-git/)

**Comment by CMCDragonkai** [comment]
Cool. I have to try it. However I work through all the capabilities I need and see what can be mix and matched or contributed back to your project. I'm almost got the right data structure index for git config. Found a good paper on this using order index and nested intervals. Its called Indexing Highly Dynamic Hierarchal Data by Jan Finis and others.

On 14 December 2017 16:23:50 GMT+11:00, William Hilton <notifications@github.com> wrote:
>I finished the big refactoring. You now use `isomorphic-git` like this:
>
>```js
>import { Git, fetch, push, ... } = require('isomorphic-git')
>...
>
>let repo = new Git({fs, dir})
>await fetch(repo, fetchOptions);
>...
>
>await push(repo, pushOptions);
>...
>```
>
>This was a compromise between having `new Git()` return the kitchen
>sink of all functionality (bad for bundle size) and having to pass
>`fs`, `gitdir`, and `workdir` every time. What do you think? Will the
>new API work better for your project? [new isomorphic-git API
>documentation website](https://wmhilton.github.io/isomorphic-git/)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/MatrixAI/js-virtualgit/issues/2#issuecomment-351612233

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
